version: "3"
services:
  app:
    container_name: mistho-scrapper
    restart: always
    build: .
    image: dockerfile
    ports:
      - "3000:3000"
      - "3001:3001"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"